### ISSUE TITLE
Windows Python help

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/fellows#187]
@IamMelvin5 and @KKidambasi have been having issues using Pip to install Frictionless on Windows. @aivuk has volunteered to help troubleshoot.

Let's find a time that works for the 4 of us to have a call. Would next Tuesday at 1pm UTC or Wednesday at 2pm UTC work for you all (note: the Tuesday time is my normal 1-on-1 with Melvin & the Wednesday time is my normal 1-on-1 with KK).

**Comment by lwinfree** [comment]
CC @lagypin

**Comment by KKidambasi** [comment]
Hi @lwinfree,

I am comfortable with Wednessday.

**Comment by lwinfree** [comment]
Closing since Edgar fixed the problem :-)
