### ISSUE TITLE
Fix sizing of pics in the blogs

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/fellows#32]
To Do: Fix sizing of pics in the blogs
Please preserve this line to notify @lwinfree (lead of this repository)

**Comment by lwinfree** [comment]
@seleneyang I've made an issue here so I will remember to look into this later :-)

**Comment by seleneyang** [comment]
Awesome! Thank you!

**Comment by lwinfree** [comment]
closed via PR #37
